name: Run Tests

on:
  pull_request:
    branches: "**"

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        include:
          - ruby-version: '2.7'
            bundle-gemfile: gemfiles/activesupport_5_2.gemfile
          - ruby-version: '3.0'
            bundle-gemfile: gemfiles/activesupport_6_0.gemfile
          - ruby-version: '3.1'
            bundle-gemfile: gemfiles/activesupport_6_1.gemfile
          - ruby-version: '3.2'
            bundle-gemfile: gemfiles/activesupport_7_0.gemfile

    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.bundle-gemfile }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      run: bundle exec rspec --profile 10 --format RspecJunitFormatter --out test_results/rspec.xml --format progress
    - name: Upload result
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rspec_${{ matrix.ruby-version }}.xml
        path: test_results/rspec.xml
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Rspec Tests - ${{ matrix.ruby-version }}
        path: test_results/rspec.xml
        reporter: java-junit
